/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'arduinoEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        },
        'ru': {
            'arduinoEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        },
        'zh-cn': {
            'arduinoEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        },
        'zh-tw': {
            'arduinoEsp32.description': 'Wi-Fi & Bluetooth control board with rich functions.'
        }
    },
    'extensions': {
        'en': {
            'arduinoEsp32.modeMenu.input': 'input',
            'arduinoEsp32.modeMenu.output': 'output',
            'arduinoEsp32.modeMenu.inputPullup': 'input-pullup',
            'arduinoEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'arduinoEsp32.levelMenu.high': 'high',
            'arduinoEsp32.levelMenu.low': 'low',
            'arduinoEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'arduinoEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'arduinoEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'arduinoEsp32.InterrupModeMenu.low': 'low level',
            'arduinoEsp32.InterrupModeMenu.high': 'high level',
            'arduinoEsp32.eolMenu.warp': 'warp',
            'arduinoEsp32.eolMenu.noWarp': 'no-warp',
            'arduinoEsp32.dataTypeMenu.integer': 'integer',
            'arduinoEsp32.dataTypeMenu.decimal': 'decimal',
            'arduinoEsp32.dataTypeMenu.string': 'string',
            'arduinoEsp32.category.pins': 'Pins',
            'arduinoEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'arduinoEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'arduinoEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'arduinoEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'arduinoEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'arduinoEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'arduinoEsp32.pins.esp32SetServoOutput': 'set servo pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'arduinoEsp32.pins.esp32DetachInterrupt': 'detach interrupt pin [PIN]',
            'arduinoEsp32.category.serial': 'Serial',
            'arduinoEsp32.serial.multiSerialBegin': 'serial [NO] begin baudrate [VALUE]',
            'arduinoEsp32.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'arduinoEsp32.serial.multiSerialAvailable': 'serial [NO] available data length',
            'arduinoEsp32.serial.multiSerialReadAByte': 'serial [NO] read a byte',
            'arduinoEsp32.category.data': 'Data',
            'arduinoEsp32.data.dataMap': 'map [DATA] from ([ARG0], [ARG1]) to ([ARG2], [ARG3])',
            'arduinoEsp32.data.dataConstrain': 'constrain [DATA] between ([ARG0], [ARG1])',
            'arduinoEsp32.data.dataConvert': 'convert [DATA] to [TYPE]',
            'arduinoEsp32.data.dataConvertASCIICharacter': 'convert [DATA] to ASCII character',
            'arduinoEsp32.data.dataConvertASCIINumber': 'convert [DATA] to ASCII nubmer'
        },
        'ru': {
            'arduinoEsp32.modeMenu.input': 'input',
            'arduinoEsp32.modeMenu.output': 'output',
            'arduinoEsp32.modeMenu.inputPullup': 'input-pullup',
            'arduinoEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'arduinoEsp32.levelMenu.high': 'high',
            'arduinoEsp32.levelMenu.low': 'low',
            'arduinoEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'arduinoEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'arduinoEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'arduinoEsp32.InterrupModeMenu.low': 'low level',
            'arduinoEsp32.InterrupModeMenu.high': 'high level',
            'arduinoEsp32.eolMenu.warp': 'warp',
            'arduinoEsp32.eolMenu.noWarp': 'no-warp',
            'arduinoEsp32.dataTypeMenu.integer': 'integer',
            'arduinoEsp32.dataTypeMenu.decimal': 'decimal',
            'arduinoEsp32.dataTypeMenu.string': 'string',
            'arduinoEsp32.category.pins': 'Pins',
            'arduinoEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'arduinoEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'arduinoEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'arduinoEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'arduinoEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'arduinoEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'arduinoEsp32.pins.esp32SetServoOutput': 'set servo pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'arduinoEsp32.pins.esp32DetachInterrupt': 'detach interrupt pin [PIN]',
            'arduinoEsp32.category.serial': 'Serial',
            'arduinoEsp32.serial.multiSerialBegin': 'serial [NO] begin baudrate [VALUE]',
            'arduinoEsp32.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'arduinoEsp32.serial.multiSerialAvailable': 'serial [NO] available data length',
            'arduinoEsp32.serial.multiSerialReadAByte': 'serial [NO] read a byte',
            'arduinoEsp32.category.data': 'Data',
            'arduinoEsp32.data.dataMap': 'map [DATA] from ([ARG0], [ARG1]) to ([ARG2], [ARG3])',
            'arduinoEsp32.data.dataConstrain': 'constrain [DATA] between ([ARG0], [ARG1])',
            'arduinoEsp32.data.dataConvert': 'convert [DATA] to [TYPE]',
            'arduinoEsp32.data.dataConvertASCIICharacter': 'convert [DATA] to ASCII character',
            'arduinoEsp32.data.dataConvertASCIINumber': 'convert [DATA] to ASCII nubmer'
        },
        'zh-cn': {
            'arduinoEsp32.modeMenu.input': 'input',
            'arduinoEsp32.modeMenu.output': 'output',
            'arduinoEsp32.modeMenu.inputPullup': 'input-pullup',
            'arduinoEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'arduinoEsp32.levelMenu.high': 'high',
            'arduinoEsp32.levelMenu.low': 'low',
            'arduinoEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'arduinoEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'arduinoEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'arduinoEsp32.InterrupModeMenu.low': 'low level',
            'arduinoEsp32.InterrupModeMenu.high': 'high level',
            'arduinoEsp32.eolMenu.warp': 'warp',
            'arduinoEsp32.eolMenu.noWarp': 'no-warp',
            'arduinoEsp32.dataTypeMenu.integer': 'integer',
            'arduinoEsp32.dataTypeMenu.decimal': 'decimal',
            'arduinoEsp32.dataTypeMenu.string': 'string',
            'arduinoEsp32.category.pins': 'Pins',
            'arduinoEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'arduinoEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'arduinoEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'arduinoEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'arduinoEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'arduinoEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'arduinoEsp32.pins.esp32SetServoOutput': 'set servo pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'arduinoEsp32.pins.esp32DetachInterrupt': 'detach interrupt pin [PIN]',
            'arduinoEsp32.category.serial': 'Serial',
            'arduinoEsp32.serial.multiSerialBegin': 'serial [NO] begin baudrate [VALUE]',
            'arduinoEsp32.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'arduinoEsp32.serial.multiSerialAvailable': 'serial [NO] available data length',
            'arduinoEsp32.serial.multiSerialReadAByte': 'serial [NO] read a byte',
            'arduinoEsp32.category.data': 'Data',
            'arduinoEsp32.data.dataMap': 'map [DATA] from ([ARG0], [ARG1]) to ([ARG2], [ARG3])',
            'arduinoEsp32.data.dataConstrain': 'constrain [DATA] between ([ARG0], [ARG1])',
            'arduinoEsp32.data.dataConvert': 'convert [DATA] to [TYPE]',
            'arduinoEsp32.data.dataConvertASCIICharacter': 'convert [DATA] to ASCII character',
            'arduinoEsp32.data.dataConvertASCIINumber': 'convert [DATA] to ASCII nubmer'
        },
        'zh-tw': {
            'arduinoEsp32.modeMenu.input': 'input',
            'arduinoEsp32.modeMenu.output': 'output',
            'arduinoEsp32.modeMenu.inputPullup': 'input-pullup',
            'arduinoEsp32.modeMenu.inputPulldown': 'input-pulldown',
            'arduinoEsp32.levelMenu.high': 'high',
            'arduinoEsp32.levelMenu.low': 'low',
            'arduinoEsp32.InterrupModeMenu.risingEdge': 'rising edge',
            'arduinoEsp32.InterrupModeMenu.fallingEdge': 'falling edge',
            'arduinoEsp32.InterrupModeMenu.changeEdge': 'change edge',
            'arduinoEsp32.InterrupModeMenu.low': 'low level',
            'arduinoEsp32.InterrupModeMenu.high': 'high level',
            'arduinoEsp32.eolMenu.warp': 'warp',
            'arduinoEsp32.eolMenu.noWarp': 'no-warp',
            'arduinoEsp32.dataTypeMenu.integer': 'integer',
            'arduinoEsp32.dataTypeMenu.decimal': 'decimal',
            'arduinoEsp32.dataTypeMenu.string': 'string',
            'arduinoEsp32.category.pins': 'Pins',
            'arduinoEsp32.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'arduinoEsp32.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'arduinoEsp32.pins.esp32SetPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32SetDACOutput': 'set dac pin [PIN] out [OUT]',
            'arduinoEsp32.pins.readDigitalPin': 'read digital pin [PIN]',
            'arduinoEsp32.pins.readAnalogPin': 'read analog pin [PIN]',
            'arduinoEsp32.pins.esp32ReadTouchPin': 'read touch pin [PIN]',
            'arduinoEsp32.pins.esp32SetServoOutput': 'set servo pin [PIN] out [OUT]',
            'arduinoEsp32.pins.esp32AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'arduinoEsp32.pins.esp32DetachInterrupt': 'detach interrupt pin [PIN]',
            'arduinoEsp32.category.serial': 'Serial',
            'arduinoEsp32.serial.multiSerialBegin': 'serial [NO] begin baudrate [VALUE]',
            'arduinoEsp32.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'arduinoEsp32.serial.multiSerialAvailable': 'serial [NO] available data length',
            'arduinoEsp32.serial.multiSerialReadAByte': 'serial [NO] read a byte',
            'arduinoEsp32.category.data': 'Data',
            'arduinoEsp32.data.dataMap': 'map [DATA] from ([ARG0], [ARG1]) to ([ARG2], [ARG3])',
            'arduinoEsp32.data.dataConstrain': 'constrain [DATA] between ([ARG0], [ARG1])',
            'arduinoEsp32.data.dataConvert': 'convert [DATA] to [TYPE]',
            'arduinoEsp32.data.dataConvertASCIICharacter': 'convert [DATA] to ASCII character',
            'arduinoEsp32.data.dataConvertASCIINumber': 'convert [DATA] to ASCII nubmer'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
